# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqueue.proto\"\x07\n\x05\x45mpty\"\x14\n\x04Item\x12\x0c\n\x04item\x18\x01 \x01(\t\"\x1c\n\x0cSizeResponse\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x16\n\x04\x46ull\x12\x0e\n\x06isFull\x18\x01 \x01(\x08\x32h\n\x05Queue\x12\x13\n\x03Put\x12\x05.Item\x1a\x05.Full\x12\x15\n\x04Peek\x12\x06.Empty\x1a\x05.Item\x12\x14\n\x03Pop\x12\x06.Empty\x1a\x05.Item\x12\x1d\n\x04Size\x12\x06.Empty\x1a\r.SizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=15
  _globals['_EMPTY']._serialized_end=22
  _globals['_ITEM']._serialized_start=24
  _globals['_ITEM']._serialized_end=44
  _globals['_SIZERESPONSE']._serialized_start=46
  _globals['_SIZERESPONSE']._serialized_end=74
  _globals['_FULL']._serialized_start=76
  _globals['_FULL']._serialized_end=98
  _globals['_QUEUE']._serialized_start=100
  _globals['_QUEUE']._serialized_end=204
# @@protoc_insertion_point(module_scope)
