# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"o\n\x11\x41ppendEntriesArgs\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x13\n\x0bleader_term\x18\x02 \x01(\x05\x12\x17\n\x0f\x63ommitted_value\x18\x03 \x01(\x05\x12\x19\n\x11uncommitted_value\x18\x04 \x01(\x05\"?\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x18\n\x10heartbeat_result\x18\x02 \x01(\x08\"?\n\x0fRequestVoteArgs\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x63\x61ndidate_term\x18\x02 \x01(\x05\"8\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvote_result\x18\x02 \x01(\x08\"\x0f\n\rGetLeaderArgs\"&\n\x11GetLeaderResponse\x12\x11\n\tleader_id\x18\x01 \x01(\x05\"$\n\x0c\x41\x64\x64ValueArgs\x12\x14\n\x0cvalue_to_add\x18\x01 \x01(\x05\"\x12\n\x10\x41\x64\x64ValueResponse\"\x0e\n\x0cGetValueArgs\"!\n\x10GetValueResponse\x12\r\n\x05value\x18\x01 \x01(\x05\"\r\n\x0bSuspendArgs\"\x11\n\x0fSuspendResponse\"\x0c\n\nResumeArgs\"\x10\n\x0eResumeResponse2\xde\x02\n\x08RaftNode\x12;\n\rAppendEntries\x12\x12.AppendEntriesArgs\x1a\x16.AppendEntriesResponse\x12\x35\n\x0bRequestVote\x12\x10.RequestVoteArgs\x1a\x14.RequestVoteResponse\x12/\n\tGetLeader\x12\x0e.GetLeaderArgs\x1a\x12.GetLeaderResponse\x12,\n\x08\x41\x64\x64Value\x12\r.AddValueArgs\x1a\x11.AddValueResponse\x12,\n\x08GetValue\x12\r.GetValueArgs\x1a\x11.GetValueResponse\x12)\n\x07Suspend\x12\x0c.SuspendArgs\x1a\x10.SuspendResponse\x12&\n\x06Resume\x12\x0b.ResumeArgs\x1a\x0f.ResumeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPENDENTRIESARGS']._serialized_start=14
  _globals['_APPENDENTRIESARGS']._serialized_end=125
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=127
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=190
  _globals['_REQUESTVOTEARGS']._serialized_start=192
  _globals['_REQUESTVOTEARGS']._serialized_end=255
  _globals['_REQUESTVOTERESPONSE']._serialized_start=257
  _globals['_REQUESTVOTERESPONSE']._serialized_end=313
  _globals['_GETLEADERARGS']._serialized_start=315
  _globals['_GETLEADERARGS']._serialized_end=330
  _globals['_GETLEADERRESPONSE']._serialized_start=332
  _globals['_GETLEADERRESPONSE']._serialized_end=370
  _globals['_ADDVALUEARGS']._serialized_start=372
  _globals['_ADDVALUEARGS']._serialized_end=408
  _globals['_ADDVALUERESPONSE']._serialized_start=410
  _globals['_ADDVALUERESPONSE']._serialized_end=428
  _globals['_GETVALUEARGS']._serialized_start=430
  _globals['_GETVALUEARGS']._serialized_end=444
  _globals['_GETVALUERESPONSE']._serialized_start=446
  _globals['_GETVALUERESPONSE']._serialized_end=479
  _globals['_SUSPENDARGS']._serialized_start=481
  _globals['_SUSPENDARGS']._serialized_end=494
  _globals['_SUSPENDRESPONSE']._serialized_start=496
  _globals['_SUSPENDRESPONSE']._serialized_end=513
  _globals['_RESUMEARGS']._serialized_start=515
  _globals['_RESUMEARGS']._serialized_end=527
  _globals['_RESUMERESPONSE']._serialized_start=529
  _globals['_RESUMERESPONSE']._serialized_end=545
  _globals['_RAFTNODE']._serialized_start=548
  _globals['_RAFTNODE']._serialized_end=898
# @@protoc_insertion_point(module_scope)
