# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tic_tac_toe.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tic_tac_toe.proto\")\n\x04Move\x12\x13\n\x04mark\x18\x01 \x01(\x0e\x32\x05.Mark\x12\x0c\n\x04\x63\x65ll\x18\x02 \x01(\x05\"y\n\x04Game\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0bis_finished\x18\x02 \x01(\x08\x12\x1a\n\x06winner\x18\x03 \x01(\x0e\x32\x05.MarkH\x00\x88\x01\x01\x12\x13\n\x04turn\x18\x04 \x01(\x0e\x32\x05.Mark\x12\x14\n\x05moves\x18\x05 \x03(\x0b\x32\x05.MoveB\t\n\x07_winner\"!\n\x0eGetGameRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\x05\"7\n\x0fMakeMoveRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\x05\x12\x13\n\x04move\x18\x02 \x01(\x0b\x32\x05.Move\"\x13\n\x11\x43reateGameRequest*\'\n\x04Mark\x12\x0f\n\x0bMARK_NOUGHT\x10\x00\x12\x0e\n\nMARK_CROSS\x10\x01\x32|\n\tTicTacToe\x12\'\n\nCreateGame\x12\x12.CreateGameRequest\x1a\x05.Game\x12!\n\x07GetGame\x12\x0f.GetGameRequest\x1a\x05.Game\x12#\n\x08MakeMove\x12\x10.MakeMoveRequest\x1a\x05.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tic_tac_toe_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MARK']._serialized_start=300
  _globals['_MARK']._serialized_end=339
  _globals['_MOVE']._serialized_start=21
  _globals['_MOVE']._serialized_end=62
  _globals['_GAME']._serialized_start=64
  _globals['_GAME']._serialized_end=185
  _globals['_GETGAMEREQUEST']._serialized_start=187
  _globals['_GETGAMEREQUEST']._serialized_end=220
  _globals['_MAKEMOVEREQUEST']._serialized_start=222
  _globals['_MAKEMOVEREQUEST']._serialized_end=277
  _globals['_CREATEGAMEREQUEST']._serialized_start=279
  _globals['_CREATEGAMEREQUEST']._serialized_end=298
  _globals['_TICTACTOE']._serialized_start=341
  _globals['_TICTACTOE']._serialized_end=465
# @@protoc_insertion_point(module_scope)
